# Generated by Django 5.2.3 on 2025-10-07 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=30,
                unique=True,
                validators=[django.core.validators.EmailValidator],
            ),
        ),
    ]
