# Generated by Django 5.2.3 on 2025-10-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loging", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
