# Generated by Django 5.2.3 on 2025-10-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loging", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Counsellor", "Counsellor"),
                    ("patient", "Patient"),
                    ("intern", "intern"),
                ],
                default="Patient",
                max_length=10,
            ),
        ),
    ]
