# Generated by Django 5.2.7 on 2025-10-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loging", "0005_emailverification_customuser_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Counsellor", "Counsellor"),
                    ("patient", "Patient"),
                    ("intern", "intern"),
                    ("HR", "HR"),
                ],
                default="Patient",
                max_length=10,
            ),
        ),
    ]
