# Generated by Django 5.2.7 on 2025-10-11 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostedbyHR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                (
                    "job_location",
                    models.CharField(
                        choices=[("Remote", "Remote"), ("On-site", "On-site")],
                        max_length=100,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("Counsellor", "Counsellor"), ("Intern", "Intern")],
                        max_length=100,
                    ),
                ),
                ("job_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("job_posted_date", models.DateTimeField(auto_now_add=True)),
                ("job_duration", models.IntegerField()),
                ("job_experience", models.IntegerField()),
                ("last_date_to_apply", models.DateField()),
                (
                    "job_posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAppliedbyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(60),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "first_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("resume", models.FileField(upload_to="resumes/")),
                ("cover_letter", models.FileField(upload_to="cover_letters/")),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HRDashbaord.jobpostedbyhr",
                    ),
                ),
            ],
        ),
    ]
