# Generated by Django 5.2.7 on 2025-10-11 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRDashbaord", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostedbyhr",
            name="job_duration",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
