# Generated by Django 5.2.7 on 2025-10-11 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRDashbaord", "0002_alter_jobpostedbyhr_job_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostedbyhr",
            name="job_experience",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
