# Generated by Django 5.2.3 on 2025-10-07 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=18
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number. Either 10 digits or +91 followed by 10 digits.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("DOB", models.DateField()),
                ("address", models.TextField(max_length=50)),
                (
                    "college_name",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Psychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=18
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number. Either 10 digits or +91 followed by 10 digits.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("DOB", models.DateField()),
                ("address", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalPsycDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RCI_no", models.CharField(max_length=12)),
                (
                    "Experiance",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(40)]
                    ),
                ),
                ("Issue_date_of_license", models.DateField()),
                (
                    "psychologist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_details",
                        to="CounsellorIntern.psychologist",
                    ),
                ),
            ],
        ),
    ]
