# Generated by Django 5.2.3 on 2025-10-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0001_initial"),
        ("loging", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='Auth_id',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='loging.customuser'),
        ),
        migrations.AddField(
            model_name='interndetails',
            name='Auth_id',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='loging.customuser'),
        ),
    ]
