# Generated by Django 5.2.7 on 2025-10-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0002_auto_20251007_2236"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interndetails",
            name="Auth_id",
        ),
        migrations.RemoveField(
            model_name="psychologist",
            name="Auth_id",
        ),
    ]
