# Generated by Django 5.2.3 on 2025-10-10 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CounsellorIntern",
            "0004_interndetails_auth_id_psychologist_auth_id_and_more",
        ),
        ("userend", "0005_appointment_assigned_doctor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailylog_counsellor",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="dailylog_counsellor",
            name="present",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dailylog_counsellor",
            name="working_day",
            field=models.CharField(
                choices=[
                    ("Full", "Full"),
                    ("First Half", "First Half"),
                    ("Second Half", "Second Half"),
                ],
                default="Full",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Dailylog_Counserllor_patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userend.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyNotification_Counsellor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userend.appointment",
                    ),
                ),
            ],
        ),
    ]
