# Generated by Django 5.2.7 on 2025-10-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0005_alter_dailylog_counsellor_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog_counserllor_patient",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailylog_counserllor_patient",
            name="meeting_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
