# Generated by Django 5.2.7 on 2025-10-11 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0006_dailylog_counserllor_patient_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(help_text="Full transcript of the meeting"),
                ),
                (
                    "summary",
                    models.TextField(help_text="AI-generated summary of the meeting"),
                ),
                (
                    "key_points",
                    models.JSONField(
                        default=list,
                        help_text="List of key points extracted from the meeting",
                    ),
                ),
                (
                    "sentiment_analysis",
                    models.JSONField(
                        default=dict, help_text="Sentiment analysis results"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated recommendations based on the session",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="CounsellorIntern.dailylog_counserllor_patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Summary",
                "verbose_name_plural": "Meeting Summaries",
                "ordering": ["-created_at"],
            },
        ),
    ]
