# Generated by Django 5.2.3 on 2025-10-04 00:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Psychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=18
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number. Either 10 digits or +91 followed by 10 digits.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("DOB", models.DateField()),
                ("address", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="InternDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=18
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number. Either 10 digits or +91 followed by 10 digits.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("DOB", models.DateField()),
                ("address", models.TextField(max_length=50)),
                (
                    "college_name",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number. Either 10 digits or +91 followed by 10 digits.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("non-binary", "non-binary"),
                            ("other", "other"),
                            ("prefer not to say", "prefer not to say"),
                        ],
                        max_length=18,
                    ),
                ),
                ("DOB", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalPsycDetails",
            fields=[
                ("RCI_no", models.CharField(max_length=12)),
                (
                    "Experiance",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(40)]
                    ),
                ),
                ("Issue_date_of_license", models.DateField()),
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="registeruser.psychologist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPrefreference",
            fields=[
                ("preferred_date", models.DateField()),
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="registeruser.userprofile",
                    ),
                ),
                ("today_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "present",
                    models.BooleanField(
                        choices=[("y", "yes"), ("n", "no")], max_length=3
                    ),
                ),
                (
                    "working_day",
                    models.CharField(
                        choices=[("Full", "Full"), ("Half", "Half")], max_length=10
                    ),
                ),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registeruser.psychologist",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "doctor")},
            },
        ),
    ]
