# Generated by Django 5.2.3 on 2025-10-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registeruser", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalpsycdetails",
            name="id",
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dailylog",
            name="doctor",
        ),
        migrations.DeleteModel(
            name="InternDetails",
        ),
        migrations.RemoveField(
            model_name="userprefreference",
            name="id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdditionalPsycDetails",
        ),
        migrations.DeleteModel(
            name="DailyLog",
        ),
        migrations.DeleteModel(
            name="Psychologist",
        ),
        migrations.DeleteModel(
            name="UserPrefreference",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
