# Generated by Django 5.2.7 on 2025-10-07 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, spaces, and hyphens are allowed.",
                                regex="^[a-zA-Z\\s-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number. Either 10 digits or +91 followed by 10 digits.",
                                regex="^(\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("appointment_date", models.DateField()),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("30", "30"),
                            ("45", "45"),
                            ("60", "60"),
                            ("90", "90"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("individual", "individual"),
                            ("couples", "couples"),
                            ("family", "family"),
                            ("group", "group"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("Prefer not to say", "Prefer not to say"),
                            ("others", "others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
