# Generated by Django 5.2.7 on 2025-10-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0003_remove_interndetails_auth_id_and_more"),
        ("userend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="selected_doctor",
            field=models.ForeignKey(
                choices=[
                    (1, "Dr. Kavita Sharma"),
                    (2, "Dr. Rajesh Patel"),
                    (3, "Dr. Sunita Verma"),
                    (4, "Dr. Manoj Singh"),
                    (5, "Dr. Anita Jain"),
                    (6, "Dr. Suresh Mehta"),
                    (7, "Dr. Neha Pandey"),
                    (8, "Dr. Amit Nair"),
                    (9, "Dr. Priya Reddy"),
                    (10, "Dr. Vikram Kumar"),
                    (17, "Admin User"),
                    (18, "t s"),
                ],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_doctor",
                to="CounsellorIntern.psychologist",
            ),
        ),
    ]
