# Generated by Django 5.2.3 on 2025-10-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0002_appointment_selected_doctor"),
    ]

    operations = []
