# Generated by Django 5.2.7 on 2025-10-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0003_auto_20251007_2323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="email",
        ),
    ]
