# Generated by Django 5.2.3 on 2025-10-10 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0005_alter_dailylog_counsellor_date_and_more"),
        ("userend", "0005_appointment_assigned_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="IsPending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="Assigned_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_assigned_doctor",
                to="CounsellorIntern.psychologist",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="selected_doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_doctor",
                to="CounsellorIntern.psychologist",
            ),
        ),
    ]
