# Generated by Django 5.2.7 on 2025-10-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0006_appointment_ispending_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="phone",
        ),
    ]
