# Generated by Django 5.2.7 on 2025-10-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0008_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="12"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
    ]
