# Generated by Django 5.2.7 on 2025-10-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0009_appointment_created_at_alter_appointment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="created_at",
        ),
    ]
