# Generated by Django 5.2.3 on 2025-10-10 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounsellorIntern", "0005_alter_dailylog_counsellor_date_and_more"),
        ("userend", "0010_remove_appointment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="meet_link",
            field=models.URLField(
                blank=True,
                help_text="Google Meet link for the appointment",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="Assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_assigned_doctor",
                to="CounsellorIntern.psychologist",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="selected_doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_doctor",
                to="CounsellorIntern.psychologist",
            ),
        ),
    ]
