# Generated by Django 5.2.3 on 2025-10-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0011_appointment_meet_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="meet_link_type",
            field=models.CharField(
                choices=[
                    ("genuine", "Genuine Google Meet"),
                    ("fallback", "Fallback Meet Link"),
                ],
                default="fallback",
                help_text="Type of meet link generated",
                max_length=20,
            ),
        ),
    ]
