# Generated by Django 5.2.7 on 2025-10-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0012_appointment_meet_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="IsPending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="meet_link_type",
            field=models.CharField(
                choices=[("genuine", "Genuine Google Meet")],
                default="genuine",
                help_text="Type of meet link generated - only genuine Google Meet links are allowed",
                max_length=20,
            ),
        ),
    ]
