# Generated by Django 5.2.7 on 2025-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userend", "0013_alter_appointment_ispending_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="meet_link_type",
        ),
        migrations.AddField(
            model_name="appointment",
            name="audio_recording",
            field=models.FileField(blank=True, null=True, upload_to="recordings/"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="room_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="meet_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
